Fix time out exception that Adam was seeing when deploying FHIR
The following exception trace was reported by Adam:

```
SRVE0283E: Exception caught while initializing context:
java.lang.RuntimeException: Encountered an exception while initializing
the servlet context.
	at com.ibm.fhir.server.listener.FHIRServletContextListener.contextInitialized(FHIRServletContextListener.java:208)
	at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:2433)
	at [internal classes]
Caused by: javax.transaction.RollbackException
```

The IBM FHIR team recommended increasing a transaction manager timeout
via an environment variable. This commit implements that by default on
the alvearie-ingestion chart.